### ISSUE TITLE
Research: Look into switching to staticman

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#106]
How feasible would it be to switch to staticman for comments. I'd like to avoid the spammy ads that come with Disqus.

https://mademistakes.com/articles/jekyll-static-comments/

**Comment by shredtechular** [comment]
I have reviewed the Staticman docs and associated walk-through articles on how to setup Staticman on a Jekyll site.  It is a very interesting solution and would be something cool to work on.  Overall, I think on a feasibility scale of 1-10 though, I'd put these around a 7 or 8.  

I feel like there are a lot of moving parts that this solution adds to your tech stack to make this solution work (GitHub's API, Staticman Saas or local app, potentially the GitHub interface itself for moderating comments, and potentially a mail server for notifications).  These additional pieces, IMO, will make local development more complex for this task as well as future tasks.  My belief is that development solutions should be easily mimic'ed from environment to environment and in my opinion, this solution is not easily mimic'ed for local development which could lead to future problems.  This solution doesn't appear to be one that goes through a lot of non-production steps and is more simply "winged" in production.  Not to mention, there are no more points of failure within the site, so I would recommend more error handling to be introduced if it isn't already built in with the solution/theme.

My opinion, if you are thinking about this route is, why not just build your own version of disqus without the ads that you can host along with your site?  That would avoid the spammy ads, you'd have complete control over asthetics, data, and even notifications.  And you would eliminate adding potentially 4 external dependencies.

However, If you would like to try this solution, I think there are a number of questions to answer up-front on the solution before we fully develop an approach.

### Initial questions to be answered:
1. Is your intent to use the SaaS version of Staticman or run your version of it on your own server?  I can see pros/cons of each.  From my perspective this is the biggest decision and really impacts local development.
2. Currently local development doesn't build with comments, but moving forward with this solution I imagine we would want to develop with comments enabled?
3. Do you envision using the theme's default form/js for the comments?  Or is there customization you would like there?
4. How do you want to handle comment moderation?  You can have comments come into your repo as pull requests or unmoderated.
5. Do you want notifications for users when a comment is successfully added?  Replied too?
6. What notifications do you want as the moderator?  Anytime a comment/reply is added?
7. For notifications do you plan on setting up a mailgun account?
8. There are steps that would need to be taken as the admin of the repo to enable communication from github and staticman.  Is that something you would handle I assume?
9. Do you want nested commenting that is currently in disqus?

### Too early thoughts on approach for implementation:
1. Setup a separate feature branch to do pull requests against.
2. Create/Enable comment form
3. Configure staticman with repo(s).  Probably would need to figure out some kind of test environment to do this in to begin with.
4. Create/Enable form submission js
5. Configure notifications
6. Create/Enable display of entered comments.
7. Initial migration of existing comments
8. Update any build/test/deployment scripts
9. Testing and feedback rounds
10. Before going live:
    1. Commenting freeze on live site
    2. Configure components on production systems
    3. Final comment migration
    4. Merge feature branch into master
11. Update docs with maintenance procedures, local dev, and testing notes.

**Comment by mtlynch** [comment]
Sorry for the delay. Thanks for the research! Very helpful.

I think staticman would add enough complexity that I'm fine just sticking with Disqus. I seem to have dialed down the ad spamminess in settings and if I *really* need to get rid of ads via Disqus, the dev cost of migrating to staticman is high enough that it's worth just paying Disqus the $10/mo to turn ads off.
