### ISSUE TITLE
Re-organize the site's local CSS to follow a traditional SASS/SCSS model

### ISSUE THREAD

**Issue by shredtechular** [mtlynch/mtlynch.io#143]
Currently, all of the custom CSS that needs to be developed and extended outside of the parent theme's CSS has been stored in the `/assets/css/main.scss` file.  There is nothing wrong with this and it will work, however, if customizations to css were to continue, then eventually that main.scss file could become a bit untidy and possibly more difficult to maintain.  I think we can add a little more organization to the custom css by breaking it out into individual .scss files that are then compiled, along with the parent theme's .scss files, into the final main.css file that the site serves on the live website.

I originally and mistakenly understood that when building the site, the parent theme's _sass folder would completely overwrite anything we added to a local _sass directory and didn't think following a traditional SASS structure would be possible.  However, after a small experiment, I think is possible and could be beneficial from a maintainability perspective.

I would propose breaking out the `/assets/css/main.scss` file into .scss files within a `/_sass/child-theme/` directory.  In other words in the `/assets/css/main.scss` file, instead of all the custom css inside of that file, we would have a simple SASS include like:
```
@import "child-theme/main";
```
And then we could breakout all of the existing custom css into a SASS directory structure of .scss files, something similar to:
```
_sass
  |-> child-theme
     |-> base
        |-> _base.scss
     |-> components
        |-> _tabs.scss
     |-> helpers
        |-> _variables.scss
        |-> _mixins.scss
     main.scss
```

I think the main benefit here is really just maintainability and organization of CSS, so this doesn't need to be a really high priority, but just something to think about if it is worth it to do.

**Comment by mtlynch** [comment]
Oh, cool. I like this idea. I've added it to the project queue.
