### ISSUE TITLE
Right aligned image causing ugly breaks

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#161]
I'm working on a new post draft in the `code-reviews` branch. Preview is 

http://preview.mtlynch.io/human-code-reviews/

I noticed that on mobile, the right-aligned image causes really weird line breaks.

![image](https://user-images.githubusercontent.com/7783288/30994115-4e8c945a-a480-11e7-8268-cb6fca22910f.png)

This might be something I have to be aware of when picking image sizes, but I wanted to check if there was anything that can be done in 

The ideal behavior would be that when there's so little horizontal space, the image would stop allowing text to float next to it and just expand to fill the space. But I realize that's probably hard to pull off, but I wanted to see if there are options that might make this scenario go smoother on mobile.

**Comment by shredtechular** [comment]
Good catch, I didn't even notice this... I can replicate this on my end and am working on it now.
