### ISSUE TITLE
Research: Regenerate all sizes of an image after it's modified

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#171]
I've noticed that if I modify an image after it's already been resized, Jekyll doesn't regenerate the smaller sizes of the image.

Not really an issue in production because the images all get resized from scratch anyway, but it would be handy in development. I've been working around this by deleting the files manually from the `resized` folder.

How difficult would this be to fix automatically? So that every time an image file under `images/` is touched, Jekyll regenerates its resized versions.

**Comment by shredtechular** [comment]
My initial thoughts are:

I upgraded the jekyll-responsive-image to v1.4 on my local environment and doing that will allow us to create the `resized` folder in the _site directory.  So given that, I think our options are:

1. [Low effort] - As part of the `_serve_dev.sh` build process run `jekyll clean` which will in essence automate the removal of the `resized` folder along with the `_site` directory before each build.  

2. [Low effort] - Performing option 1 on EVERY build could become cumbersome as all images would need to regenerate on every build.  So, we could fancy option #1 up a little more by passing in a `-clean` flag to specifically run clean so it isn't run before EACH build, only on builds when the `clean` flag is passed in.  So, if you knew you modified an image you could run `./script/_serve_dev.sh -clean`.

3. [Higher effort] - Implement a task that looks at image modified dates and removes `resized` images that have an older modified date than its associated original image.  Pretty sure this would be doable, but I don't think very trivial (at least not for me! 😄 ).

I guess, my questions before finalizing on an option would be:
1. For your normal workflow, do you use incremental building at all?  Or do you run the `script/_serve_dev.sh` for each build?

2. Does the use-case for modifying images happen often enough where regenerating all images locally become cumbersome?  Totally fine if so, but just want to confirm before recommending the highest effort option.

**Comment by mtlynch** [comment]
Thanks for looking into these, Andrew! Good info.

I think (1) is a bit too intrusive to the normal workflow. (2) is good, but I don't think it ends up winning us much more than doing something like `jekyll clean && ./script/_serve_dev.sh`. (3) sounds a bit too costly relative to the scale of the problem.

I'm happy to leave it as is for the time being. If you come upon a solution you think might work in the future, happy to open it up again.
