### ISSUE TITLE
Bug: Ipad display issue for blog posts

### ISSUE THREAD

**Issue by shredtechular** [mtlynch/mtlynch.io#192]
During some recent testing, I noticed a display issue on landscape views for tablets.  I know this affects ipads and probably other devices with similar browser widths.  I will submit a fix for this, but also wanted to document quickly as an issue for reference/tracking.

Below is a screen-cap of what I see on ipad (landscape), as you can see the actual article content is pushed down as there is a space overlapping issue between the sidebar and article itself.

<kbd>
<img width="768" alt="screen shot 2017-11-11 at 4 43 16 pm" src="https://user-images.githubusercontent.com/2396774/32693854-efdd2a08-c6ff-11e7-815c-736626fbed15.png">
</kbd>

**Comment by mtlynch** [comment]
Thanks for catching this!
