### ISSUE TITLE
Include literal double quote in fig_caption parameter

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#206]
I'd like to include a literal double quote character in a figure caption. Is this possible?

I tried the following:

```
{% assign fig_caption = "\"Appeal to Ignorance\", from [*An Illustrated Book of Bad Arguments*](http://amzn.to/2jy2vND)" | markdownify | remove: "<p>" | remove: "</p>" %}

{% include image.html file="boba-appeal-to-ignorance.png" alt="Appeal to Ignorance image" max_width="400px" fig_caption=fig_caption %}
```

But then Jekyll produces this warning and doesn't render the caption:

```
Liquid Warning: Liquid syntax error (line 40): Unexpected character \ in "{{"\"Appeal to Ignorance\", from [*An Illustrated Book of Bad Arguments*](http://amzn.to/2jy2vND)" | markdownify | remove: "<p>" | remove: "</p>" }}" in /home/mike/mtlynch.io/_posts/2017-11-14-how-to-hire-a-cartoonist-for-your-blog.md
```

I'd like the caption to be:

>"Appeal to Ignorance", from [*An Illustrated Book of Bad Arguments*](http://amzn.to/2jy2vND)

**Comment by shredtechular** [comment]
@mtlynch after doing some testing locally, from what I can tell, it appears to be the responsive image plugin that is breaking when trying to do typical liquid escaping for quotes.  I tried escaping using HTML entity and unicode as well and the plugin seems to not handle escaped strings.

Therefore, I can think of the following 3 options from easiest to more complicated:
1. The easiest option is to simply use single quotes to encapsulate the figure caption string if you'd like to use a literal double quote.  If you'd like to use single quotes in the figure caption string, then encapsulate the string with double quotes.  This solution obviously breaks down if you want to use **BOTH** literal single & double quotes in the figure caption string (not sure if this would ever be a use case?).  To use your specific example, this will work properly:
```
{% assign fig_caption = '"Appeal to Ignorance", from [*An Illustrated Book of Bad Arguments*](http://amzn.to/2jy2vND)' | markdownify | remove: "<p>" | remove: "</p>" %}
```

2. If you feel like you ever may need to use single **AND** double quotes in the same caption string, then we could create our own unique sequence of characters that we could then do a replace function to substitute the proper literal string in the `responsive-image.html` template.  For example, we could do something like:
```
{% assign fig_caption = "~~dQuote~~Appeal to Ignorance~~dQuote~~, some phrase with ~~sQuote~~single quotes~~sQuote~~ around it" | markdownify | remove: "<p>" | remove: "</p>" %}
```
Then in the responsive-image.html template we could do a replace on `~~dQuote~~` to make those `"` and `~~sQuote~~` to make those `'`.
This is a pretty simple code change if you'd like me to incorporate this solution?  And we can use whatever combo of characters for the substitution.

3. The last option, and probably more of a reach/lots of effort involved, would be to see if we could fix this capability within the plugin...not sure I'm real comfortable doing that, but can certainly look more into this.  I could also open an issue in their repo to see if they are aware of this issue.

**Comment by mtlynch** [comment]
Haha, I didn't think of using single quotes (1). That works well enough for now. Thanks!
