### ISSUE TITLE
Run build steps in Docker container

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#221]
I'd like to change the Travis config to use Docker to run the build tests and produce the production site files.

~~There is a similar example of this in one of my other projects (building a static site with Angular rather than Jekyll). The particulars are different, but we want to use the same general structure:~~

1. ~~The [Dockerfile](https://github.com/mtlynch/ketohub_web_app/blob/master/Dockerfile) copies the local source folder into the Docker image's `/app` directory.~~
1. ~~The [Dockerfile](https://github.com/mtlynch/ketohub_web_app/blob/master/Dockerfile) runs all the build tests.~~
1. ~~The [Dockerfile](https://github.com/mtlynch/ketohub_web_app/blob/master/Dockerfile) ultimately creates a production build by running the npm [build script](https://github.com/mtlynch/ketohub_web_app/blob/1eabed495eb67c240b6cb65e01d5a4cec92814d8/package.json#L7)~~
1. ~~The [.travis.yml](https://github.com/mtlynch/ketohub_web_app/blob/ab5af15920da64a512aead7fdcd414645bf566ec/.travis.yml#L12-L13) builds and runs the Docker image defined above~~
1. ~~The [.travis.yml](https://github.com/mtlynch/ketohub_web_app/blob/ab5af15920da64a512aead7fdcd414645bf566ec/.travis.yml#L14) copies the Docker container's `/app/dist` folder (which contains the production build files) to the host's `./dist` folder.~~

Instead of the [node:8-stretch](https://github.com/mtlynch/ketohub_web_app/blob/815fdba2c510ddcfc350bd4e580d058b6e1435f6/Dockerfile#L1) base image, we'll use the [jekyll/jekyll](https://github.com/envygeeks/jekyll-docker/blob/master/README.md) Docker image.

~~Then we would get rid of the existing [build file](https://github.com/mtlynch/mtlynch.io/blob/master/_tests/build) and move those steps to a Dockerfile, like in the ketohub_web_app example. We can get rid of the `--quick` flag because it's not worth trying to reimplement that in a Dockerfile.~~

**Update**: I think I have a better design. See below

**Comment by mtlynch** [comment]
I realized it would be easier if I just showed the strategy I have in mind:

https://github.com/mtlynch/mtlynch.io/pull/224

It's partially done, but it's failing with a Unicode conversion error I can't figure out. Do you want to copy that PR and work on getting it to successful build so that it achieves the same functionality as our current build process?

**Comment by shredtechular** [comment]
@mtlynch I worked on your `docker-build` branch and fixed the Unicode conversion error so it is building successfully now.  I think that was really the last hurdle in getting the same functionality as our current build process as it looked like you hooked everything else up that I can see.  I also tested some Markdown Linter failures and HTMLProofer errors and the process exits properly.

I did have one question before I check that PR in though.  In the original task, it stated:
> Instead of the node:8-stretch base image, we'll use the jekyll/jekyll Docker image.

It looks like the Dockerfile created in #224 is using the `node:8-stretch` image if I'm understanding that correctly?  Did you want to still use the `jekyll/jekyll` image or would you prefer to leave the `node:8-stretch` image in place?

**Comment by mtlynch** [comment]
Awesome! Can you submit the PR?

>>Instead of the node:8-stretch base image, we'll use the jekyll/jekyll Docker image.

>It looks like the Dockerfile created in #224 is using the node:8-stretch image if I'm understanding that correctly? Did you want to still use the jekyll/jekyll image or would you prefer to leave the node:8-stretch image in place?

Yeah, I initially thought that made more sense, but then I ran into dependency issues when I tried to use the `jekyll/jekyll` image. I can't remember what they are now. I should have recorded that.

I think the issue was that I couldn't figure out how to install bundler and get the dependencies installed, so it was easier to just install it the way we have been installing in Travis.

**Comment by shredtechular** [comment]
OK, got it that makes sense!  Seems like it doesn't really matter what image is used as long as you can do what you need to do in the container and understand it so keeping it as-is sounds good!  I'll create a PR!
