### ISSUE TITLE
Frontmatter tests fail even after fixing frontmatter errors

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#279]
I notice there's a bug with the frontmatter test where, after failing, it gets into a bad state where jekyll will crash even when the frontmatter issue is resolved.

Example:

```bash
# Delete necessary key from frontmatter.
$ sed -i '/header:/d' _posts/2018-05-29-since-quitting.md  && sed -i '/og_image:/d' _posts/2018-05-29-since-quitting.md

# Try to build
$ ./script/_serve_dev.sh
Testing _posts.yml

The file 2018-05-29-since-quitting.md is missing the following keys:
    * header
    * header
jekyll 3.8.2 | Error:  wrong number of arguments (given 2, expected 1)

# Undo the changes (fix the problem)
$ git checkout -- _posts/2018-05-29-since-quitting.md

# Try to build again
$ ./script/_serve_dev.sh

> minimal-mistakes@4.9.0 build:js /tmp/mtlynch.io
> npm run uglify


> minimal-mistakes@4.9.0 uglify /tmp/mtlynch.io
.fitvids.js assets/js/plugins/jquery.greedy-navigation.js assets/js/plugins/jquery.magnific-popup.js assets/js/plugins/jquery.smooth-scroll.min.js assets/js/_main.js assets/js/_anchors.js -c -m -o assets/js/main.min.js

Configuration file: _config.yml
Configuration file: _config_dev.yml
            Source: /tmp/mtlynch.io
       Destination: /tmp/mtlynch.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Configuration file: /tmp/mtlynch.io/_config.yml
Testing _posts.yml
jekyll 3.8.2 | Error:  (#<File:0x00000003749cf0>): control characters are not allowed at line 1 column 1
```

**Expected**: Fixing the frontmatter error allows the build to work successfully.

**Actual**: Even after fixing the issue, Jekyll still fails with `jekyll 3.8.2 | Error:  (#<File:0x00000003749cf0>): control characters are not allowed at line 1 column 1`

**Comment by shredtechular** [comment]
Following the same steps, I'm not able to replicate this issue on my end.  This appears to be specific to your environment I think as something in those steps seems to be adding some unknown characters and it's breaking Jekyll's yml validation/build process.

1. Are you on OSX or WIN or other?

2. Per this [article](https://stackoverflow.com/questions/29608852/control-characters-are-not-allowed-at-line-1-column-1-psychsyntaxerror-dur?lq=1) I'm wondering if there are any of your environment variables that may be different than UTF-8?  Are you able to write out any of these like `echo $LANG`?  If I match any of the settings that you have there, wondering if I can replicate...  

3. Perhaps this is an issue with the encoding settings for either your SED or GIT as well?  If you perform these steps using a text editor and 
  1. remove the 2 lines of yaml to force the validation to error & save the file
  2. try to build with: `./script/_serve_dev.sh`
  3. undo the changes in your text editor with `ctrl+z` or `cmd+z` and save the file
  4. re-try the build with: `./script/_serve_dev.sh`
  5. same issue or does it work with the text editor that hopefully has encoding set to UTF-8?

**Comment by mtlynch** [comment]
I hit the error on Ubuntu 16.

Let me play around with it to see if I can get a clean repro for you in the Docker container so that we're using the same environment.

**Comment by mtlynch** [comment]
You were right.

I think this was just something funky in my environment. I couldn't repro in a Docker container, so I tried upgrading my node and ruby versions and then the issue went away.

Thanks for digging into this!
