### ISSUE TITLE
Support includes for .ymls beginning with dot

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#281]
The file embedding doesn't seem to work if the filename begins with a dot, like `.travis.yml`. See [`dot-travis` branch](https://github.com/mtlynch/mtlynch.io/tree/dot-travis) for an example of this:

[_ymls/restoring-vintage-python/travis](https://github.com/mtlynch/mtlynch.io/blob/dot-travis/_ymls/restoring-vintage-python/travis) has the frontmatter set to 

```yml
---
title: .travis.yml
---
```

And [2018-06-21-restoring-vintage-python.md](https://github.com/mtlynch/mtlynch.io/blob/dot-travis/_posts/2018-06-21-restoring-vintage-python.md) includes it like:

```
{% include files.html title=".travis.yml" language="yml" %}
```

But jekyll still produces the link as http://localhost:4000/files/restoring-vintage-python/travis.yml (not `.travis.yml`).

If I try renaming `_ymls/restoring-vintage-python/travis` to `_ymls/restoring-vintage-python/.travis`, jekyll doesn't render the file contents at all.

**Comment by shredtechular** [comment]
By default Jekyll doesn't render dotfiles for generation, but we do have a couple of options for overriding that default using (1) permalinks or (2) the `include:` configuration option (prefer option 2, but I think we'd have to go with option 1).  From the [jekyll configuration docs](https://jekyllrb.com/docs/configuration/):

> Force inclusion of directories and/or files in the conversion.  .htaccess is a good example since dotfiles are excluded by default.

That said, doing some local testing, even if we override and are able to render a `.travis.yml` so the "download raw" link is "/files/restoring-vintage-python/.travis.yml" when click to download it, the web browser is changing the downloaded file to `travis.yml` removing the leading dot.

So, if the goal is for the user to be able to download a specifically named ".travis.yml" file, it almost seems like we would need to put it in a zip file?  Is that the problem/goal for supporting .ymls beginning with a dot?  And if so, would you agree we would need to also have a zip file containing the file in addition to the travis file?  The bad part is then it would entail maintaining the travis file and the zip file...  any thoughts?

**Comment by mtlynch** [comment]
Oh that's a good point. I didn't realize that Chrome overrides the leading dot anyway.

In that case, it's not really worth the effort to change our URL. I can live with it just being called `travis.yml` and it's the reader's responsibility to correctly rename it.

Thanks for thinking ahead!
