### ISSUE TITLE
Book Reports: Generate a better twitter card

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#359]
The current twitter card for a book report is kind of klunky:

![image](https://user-images.githubusercontent.com/7783288/52000588-857b1180-248b-11e9-913f-43c2722dbee8.png)

I'd like it to use this same card format, but the image should be the book cover and the text should be the start of the blurb.

![image](https://user-images.githubusercontent.com/7783288/52000811-020df000-248c-11e9-8625-50c54677cc5d.png)

**Comment by mtlynch** [comment]
@shredtechular  I took a peek at #361 and I know it's going to go through a re-write, but just some quick notes:

For these spots:

* https://github.com/shredtechular/mtlynch.io/blob/15b03a65657c22d82413c49ad3ecdefa69980f62/_data/ui-text.yml#L47
* https://github.com/shredtechular/mtlynch.io/blob/15b03a65657c22d82413c49ad3ecdefa69980f62/_layouts/single.html#L55

Is the only reason localization? If so, I'd rather just inline those labels because it's unlikely that we'll ever internationalize this blog.

Also can "Amazon Link" just be hardcoded into the template? It will always be that text.

**Comment by shredtechular** [comment]
@mtlynch 

> Is the only reason localization? If so, I'd rather just inline those labels because it's unlikely that we'll ever internationalize this blog.

I wouldn't say _purely_ for localization, though that is a benefit.  I feel like the "Jekyll" way is to try to minimize **content** within template files as best as possible.  I think the theory is it is supposed to make editing **content** easier so content editor's wouldn't have to go through an html file if you ever wanted to change "My rating:" to "My score:" or something of that nature...  And of course having that file in a format that supports localization is always nice if it applies to you.

That said, when you say "inline those labels" do you mean hardcoding them into the template like you suggested with the "Amazon link" label?  We can certainly do that if you prefer, that's no problem at all.  Whatever works best for you.  If the length of those lines bothers you we can also assign variables to make that not as nasty.

**Comment by mtlynch** [comment]
Yeah so like instead of:

```html
<li>{{ site.data.ui-text[site.locale].book_report_rating | default: "My rating:" }} <strong>{{ page.report_intro.score }}</strong> / {{ site.data.ui-text[site.locale].book_report_rating_limit | default: "My rating:" }}</li>
```

I'd prefer to just hardcode it in the template itself:

```html
<li>My rating: <strong>{{ page.report_intro.score }}</strong> / 10</li>
```
