### ISSUE TITLE
License of the project missing

### ISSUE THREAD

**Issue by uzakov** [mtlynch/mtlynch.io#673]
Hi Michael!

Under what license is this project released? I did a quick search and can't find license information.
I loved your website style and would love to use it for some of my projects, if the licensing allows so

**Comment by mtlynch** [comment]
Hi @uzakov - thanks for reading! The UI is mainly the [Hugo Coder theme](https://themes.gohugo.io/hugo-coder/). I've never really bothered with a license because I'm not sure how to license my code for reuse while protecting my English content from plagiarism, though I'd welcome suggestions.

**Comment by uzakov** [comment]
Thank you for your reply Michael!

Would love to help with the license type but not an expert on the law (normally involve the legal department).

Btw you have a great blog, I found it very interesting to read.
