### ISSUE TITLE
Support center-aligned text in tables

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#90]
I'd like to have a way of center-aligning text in tables on a per-table basis. There are some tables where center-aligned would be better than the existing default of left-align, but the default should still be left-aligned.

**Comment by shredtechular** [comment]
If I'm understanding this issue correctly, this comes natively with the Kramdown markdown syntax so no code changes are needed, just markdown changes where you would like to center-align text within a table.  In [Kramdown](https://kramdown.gettalong.org/syntax.html#tables), you can specify center, left, right align by column with the default being left aligned if alignment is not specified.

You can align text to the left, right, or center of a column by including colons : to the left, right, or on both sides of the hyphens within the header row (center-aligned).

So, for example, you can do something like this:
```
| Left-aligned | Center-aligned | Right-aligned |
| :---         |     :---:      |          ---: |
| git status   | git status     | git status    |
| git diff     | git diff       | git diff      |
```

Which then gets rendered as:

| Left-aligned | Center-aligned | Right-aligned |
| :---         |     :---:      |          ---: |
| git status   | git status     | git status    |
| git diff     | git diff       | git diff      |

Does that satisfy what you are looking to do?  Or do you need the ability to center text on like a per cell basis?

**Comment by mtlynch** [comment]
Oh, cool! I didn't realize Kramdown supported this directly. I don't need anything more fine grained than at the column level, so this is great.
